version: "3"
services:
    api:
      build: .
      ports: 
        - "3004:3004"
      environment:
        -  PORT=3004
      depends_on:
        - db
        - redis
      links:
        - redis
      volumes:
        - .:/app
                  
    db:
      image: mongo
      environment:
        - MONGO_INITDB_ROOT_USERNAME=test
        - MONGO_INITDB_ROOT_PASSWORD=test
      volumes:
        - db:/data/db

    redis:
      image: redis
      ports:
        - "6379:6379"
      volumes:
        - /redis-data
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379

volumes:
  db:
  redis-data:
  app:

