version: "3"
services:
    api:
      build: .
      ports: 
        - "3004:3004"
      environment:
        -  PORT=3004
      env_file:
        - ./.env
      depends_on:
        - db
      volumes:
        - ./:/app
        - /app/node_modules
      command: npm run dev
                  
    db:
      image: mongo
      environment:
        - MONGO_INITDB_ROOT_USERNAME=test
        - MONGO_INITDB_ROOT_PASSWORD=test
      volumes:
        - db:/data/db

volumes:
  db:
  app:

